# Generated by Django 3.0.4 on 2020-04-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200424_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image_alt',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_alt',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='image',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
